### ISSUE TITLE
how to Postman with Okta during development

### ISSUE THREAD

**Issue by trevorjamesmartin** [BloomTech-Labs/labs-api-node-starter#12]
https://developer.okta.com/code/rest/

**Comment by DeeDowns** [comment]
So I created a validation middleware function that is supposed to ensure that the emoji part of the request body consists only of up to 6 emojis (no strings of words or numbers or other characters) and I would like to use postman to test this out. But I am not sure how to get the necessary headers from Okta so that I can make an authorized request. 
Trevor pointed me in the direction of setting up a Postman environment that incorporates Okta, but I dont know what to put for the apikey parameter. 
![Screen Shot 2020-12-11 at 3 12 41 PM](https://user-images.githubusercontent.com/47228065/101950514-68edab80-3bc3-11eb-9a25-325cc2e17ad1.png)
